import type { CharacterData, CharacterType, SkillTree } from "./Character";

// Define all skills for each character
const heliosSkills: SkillTree = {
  lightAttack: [
    {
      id: "helios-light-speed",
      name: "Swift Strike",
      description: "Increases light attack speed",
      maxLevel: 3,
      baseCost: 1,
      costMultiplier: 1.5,
      type: "combat" as const,
    },
    {
      id: "helios-light-damage",
      name: "Precise Hit",
      description: "Increases light attack damage",
      maxLevel: 5,
      baseCost: 2,
      costMultiplier: 1.3,
      type: "combat" as const,
    },
  ],
  heavyAttack: [
    {
      id: "helio-heavy-power",
      name: "Solar Blast",
      description: "Heavy attacks create explosive damage",
      maxLevel: 3,
      baseCost: 3,
      costMultiplier: 2.0,
      type: "combat" as const,
    },
    {
      id: "helio-heavy-range",
      name: "Solar Wave",
      description: "Heavy attacks have increased range",
      maxLevel: 2,
      baseCost: 4,
      costMultiplier: 1.8,
      type: "combat" as const,
    },
  ],
  block: [
    {
      id: "helio-block-duration",
      name: "Solar Shield",
      description: "Block lasts longer and reflects damage",
      maxLevel: 3,
      baseCost: 2,
      costMultiplier: 1.4,
      type: "combat" as const,
    },
  ],
  dodge: [
    {
      id: "helio-dodge-distance",
      name: "Solar Step",
      description: "Dash travels further distance",
      maxLevel: 3,
      baseCost: 2,
      costMultiplier: 1.3,
      type: "combat" as const,
    },
    {
      id: "helio-dodge-cooldown",
      name: "Solar Recovery",
      description: "Reduced dash cooldown",
      maxLevel: 4,
      baseCost: 1,
      costMultiplier: 1.2,
      type: "combat" as const,
    },
  ],
  unique: [
    {
      id: "helio-solar-flare",
      name: "Solar Flare",
      description: "Blinds nearby enemies with solar energy",
      maxLevel: 3,
      baseCost: 5,
      costMultiplier: 2.0,
      type: "utility" as const,
    },
    {
      id: "helio-healing-light",
      name: "Healing Light",
      description: "Regenerates health over time",
      maxLevel: 4,
      baseCost: 4,
      costMultiplier: 1.5,
      type: "passive" as const,
    },
    {
      id: "helio-solar-burn",
      name: "Solar Burn",
      description: "Attacks inflict burning damage over time",
      maxLevel: 3,
      baseCost: 6,
      costMultiplier: 1.8,
      type: "combat" as const,
    },
    {
      id: "helio-solar-storm",
      name: "Solar Storm",
      description: "Ultimate ability: massive area damage",
      maxLevel: 2,
      baseCost: 10,
      costMultiplier: 3.0,
      type: "combat" as const,
    },
  ],
};

const irisSkills: SkillTree = {
  lightAttack: [
    {
      id: "aria-light-chain",
      name: "Wind Chain",
      description: "Light attacks can chain to nearby enemies",
      maxLevel: 3,
      baseCost: 2,
      costMultiplier: 1.4,
      type: "combat" as const,
    },
    {
      id: "aria-light-speed",
      name: "Gale Force",
      description: "Increased attack and movement speed",
      maxLevel: 4,
      baseCost: 1,
      costMultiplier: 1.3,
      type: "combat" as const,
    },
  ],
  heavyAttack: [
    {
      id: "aria-heavy-tornado",
      name: "Tornado Strike",
      description: "Heavy attacks create spinning wind damage",
      maxLevel: 3,
      baseCost: 4,
      costMultiplier: 1.8,
      type: "combat" as const,
    },
  ],
  block: [
    {
      id: "aria-wind-barrier",
      name: "Wind Barrier",
      description: "Block creates a protective wind shield",
      maxLevel: 3,
      baseCost: 3,
      costMultiplier: 1.5,
      type: "combat" as const,
    },
  ],
  dodge: [
    {
      id: "aria-air-dash",
      name: "Air Dash",
      description: "Can dash through the air",
      maxLevel: 2,
      baseCost: 5,
      costMultiplier: 2.0,
      type: "utility" as const,
    },
    {
      id: "aria-dodge-multi",
      name: "Wind Steps",
      description: "Can perform multiple dashes in succession",
      maxLevel: 3,
      baseCost: 6,
      costMultiplier: 1.8,
      type: "utility" as const,
    },
  ],
  unique: [
    {
      id: "aria-whirlwind",
      name: "Whirlwind",
      description: "Creates a damaging whirlwind at target location",
      maxLevel: 3,
      baseCost: 7,
      costMultiplier: 1.8,
      type: "combat" as const,
    },
    {
      id: "aria-wind-walk",
      name: "Wind Walk",
      description: "Temporary invisibility and movement speed",
      maxLevel: 2,
      baseCost: 8,
      costMultiplier: 2.5,
      type: "utility" as const,
    },
    {
      id: "aria-updraft",
      name: "Updraft",
      description: "Launches enemies into the air",
      maxLevel: 3,
      baseCost: 5,
      costMultiplier: 1.6,
      type: "combat" as const,
    },
    {
      id: "aria-hurricane",
      name: "Hurricane",
      description: "Ultimate: massive wind storm across the battlefield",
      maxLevel: 2,
      baseCost: 12,
      costMultiplier: 3.0,
      type: "combat" as const,
    },
  ],
};

const lucySkills: SkillTree = {
  lightAttack: [
    {
      id: "zara-light-poison",
      name: "Poison Edge",
      description: "Light attacks apply poison",
      maxLevel: 4,
      baseCost: 2,
      costMultiplier: 1.3,
      type: "combat" as const,
    },
    {
      id: "zara-light-lifesteal",
      name: "Vampiric Strike",
      description: "Light attacks heal for % of damage dealt",
      maxLevel: 3,
      baseCost: 3,
      costMultiplier: 1.5,
      type: "combat" as const,
    },
  ],
  heavyAttack: [
    {
      id: "zara-heavy-curse",
      name: "Cursed Bolt",
      description: "Heavy attacks curse enemies, reducing their damage",
      maxLevel: 3,
      baseCost: 4,
      costMultiplier: 1.6,
      type: "combat" as const,
    },
  ],
  block: [
    {
      id: "zara-block-reflect",
      name: "Dark Reflection",
      description: "Blocking reflects dark energy at attackers",
      maxLevel: 3,
      baseCost: 3,
      costMultiplier: 1.4,
      type: "combat" as const,
    },
  ],
  dodge: [
    {
      id: "zara-shadow-step",
      name: "Shadow Step",
      description: "Dash leaves behind a damaging shadow",
      maxLevel: 3,
      baseCost: 3,
      costMultiplier: 1.4,
      type: "combat" as const,
    },
  ],
  unique: [
    {
      id: "zara-drain-life",
      name: "Drain Life",
      description: "Continuously drains health from nearby enemies",
      maxLevel: 4,
      baseCost: 6,
      costMultiplier: 1.7,
      type: "combat" as const,
    },
    {
      id: "zara-shadow-clone",
      name: "Shadow Clone",
      description: "Creates a shadow clone that mimics attacks",
      maxLevel: 2,
      baseCost: 10,
      costMultiplier: 2.5,
      type: "combat" as const,
    },
    {
      id: "zara-dark-aura",
      name: "Dark Aura",
      description: "Passive aura that weakens nearby enemies",
      maxLevel: 3,
      baseCost: 5,
      costMultiplier: 1.6,
      type: "passive" as const,
    },
    {
      id: "zara-void-rift",
      name: "Void Rift",
      description: "Ultimate: opens a rift that consumes enemies",
      maxLevel: 2,
      baseCost: 15,
      costMultiplier: 3.0,
      type: "combat" as const,
    },
  ],
};

const kaiSkills: SkillTree = {
  lightAttack: [
    {
      id: "kai-light-crit",
      name: "Critical Strike",
      description: "Increased critical hit chance and damage",
      maxLevel: 4,
      baseCost: 2,
      costMultiplier: 1.4,
      type: "combat" as const,
    },
    {
      id: "kai-light-combo",
      name: "Blade Combo",
      description: "Consecutive hits deal increased damage",
      maxLevel: 3,
      baseCost: 3,
      costMultiplier: 1.5,
      type: "combat" as const,
    },
  ],
  heavyAttack: [
    {
      id: "kai-heavy-shockwave",
      name: "Earth Shatter",
      description: "Heavy attacks create ground shockwaves",
      maxLevel: 3,
      baseCost: 4,
      costMultiplier: 1.7,
      type: "combat" as const,
    },
  ],
  block: [
    {
      id: "kai-block-counter",
      name: "Perfect Counter",
      description: "Successful blocks trigger automatic counterattacks",
      maxLevel: 3,
      baseCost: 4,
      costMultiplier: 1.6,
      type: "combat" as const,
    },
  ],
  dodge: [
    {
      id: "kai-dodge-attack",
      name: "Strike Dash",
      description: "Dashing through enemies deals damage",
      maxLevel: 3,
      baseCost: 3,
      costMultiplier: 1.4,
      type: "combat" as const,
    },
  ],
  unique: [
    {
      id: "kai-berserker",
      name: "Berserker Rage",
      description: "Low health increases damage and attack speed",
      maxLevel: 3,
      baseCost: 5,
      costMultiplier: 1.8,
      type: "passive" as const,
    },
    {
      id: "kai-ground-slam",
      name: "Ground Slam",
      description: "Powerful area attack that stuns enemies",
      maxLevel: 3,
      baseCost: 7,
      costMultiplier: 1.9,
      type: "combat" as const,
    },
    {
      id: "kai-weapon-throw",
      name: "Weapon Throw",
      description: "Throws weapon as a boomerang projectile",
      maxLevel: 3,
      baseCost: 6,
      costMultiplier: 1.6,
      type: "combat" as const,
    },
    {
      id: "kai-earthquake",
      name: "Earthquake",
      description: "Ultimate: causes massive battlefield earthquake",
      maxLevel: 2,
      baseCost: 12,
      costMultiplier: 3.0,
      type: "combat" as const,
    },
  ],
};

// Character definitions
export const CHARACTERS: Record<CharacterType, CharacterData> = {
  helio: {
    name: "Helios",
    description: "Solar warrior seeking revenge for his murdered parents",
    color: "#4ec9ff",
    skillTrees: heliosSkills,
  },
  aria: {
    name: "Iris",
    description: "Wind master with swift and agile combat style",
    color: "#7fff7f",
    skillTrees: irisSkills,
  },
  zara: {
    name: "Lucy",
    description: "Dark sorceress wielding shadow and void magic",
    color: "#bf7fff",
    skillTrees: lucySkills,
  },
  kai: {
    name: "Kai",
    description: "Earth guardian with powerful melee combat techniques",
    color: "#ffbf7f",
    skillTrees: kaiSkills,
  },
};
